# Configuration for the labeler action
# https://github.com/actions/labeler

# Add 'documentation' label to any changes within docs folders or markdown files
documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'README*'

# Add 'frontend' label to UI-related files
frontend:
  - 'src/**/*'
  - 'public/**/*'
  - '**/*.vue'
  - '**/*.js'
  - '**/*.ts'
  - '**/*.jsx'
  - '**/*.tsx'
  - '**/*.css'
  - '**/*.scss'
  - '**/*.sass'
  - '**/*.less'

# Add 'dependencies' label to dependency files
dependencies:
  - 'package.json'
  - 'package-lock.json'
  - 'pnpm-lock.yaml'
  - 'yarn.lock'

# Add 'ci/cd' label to GitHub Actions and deployment files
ci/cd:
  - '.github/**/*'
  - 'Dockerfile*'
  - 'docker-compose*'
  - 'firebase.json'
  - '.firebaserc'

# Add 'configuration' label to config files
configuration:
  - '**/*.config.js'
  - '**/*.config.ts'
  - '.env*'
  - 'tsconfig.json'
  - 'vite.config.*'
  - 'tailwind.config.*'
